#!/bin/bash

source=$1
dest=$source.converted

# Convert the file
/usr/bin/HandBrakeCLI -i $source -o $dest

# Check to see if everything looks right
if [ -e $dest ] 
then
 echo $dest
else
 echo $source
fi



