#!/bin/bash

# Expand these first..
source="$1"
dest="$source.converted"

log $(date)" : $source $dest"

# Common
source "${0%/*}/config/common"
source "${0%/*}/config/machine"

# Get the convert command
if [ ! "$videoConvert" == "" ] 
then
{
	# Issue the conversion command
	eval "$videoConvert"

	# Check to see if the thing converted
	if [ -e $dest ] 
	then
	 echo $dest
	else
	 echo $source
	fi

} || tee -a $logFile

fi



