#!/bin/bash


# Common
source "${0%/*}/config/common"
source "${0%/*}/config/machine"

log "Fetch starting"

item=$1
if [ "$item" == "" ]
then
 echo "No item provided."
 exit 1
fi


#item=${1,,}
#itemProper=${item^}
#urlSetting="url$itemProper"
# Get the value of that setting
#url=${!urlSetting}


case "$1" in

    "schedule" ) url="$urlSchedule"
                 configFile="config/schedule-remote"
                 ;;

             * ) echo "No URL found for $1"
                 exit 1
                 ;;
esac


if [ -z "$configFile" ]
then
 log "Backing up $configFile"
 mv "$configFile" "$configFile.bak"
fi

log "URL=$url"
log "File=$configFile"
curl --silent "$url" > "$configFile"

log "Fetch completed."
exit 0

