#!/bin/bash


# Common
source "${0%/*}/config/common"

log "Fetch starting"

item=${1,,}

itemProper=${item^}
urlSetting="url$itemProper"

url=${!urlSetting}

# Validations..
if [ "$item" == "" ]
then
 echo "No item provided."
 exit 1
fi

if [ "$url" == "" ]
then
 echo "No URL found for $item"
 exit 1
fi

# We have an URL, let's go get the data
configFile="config/$item"
if [ -z "$configFile" ]
then
 log "Backing up $configFile"
 mv "$configFile" "$configFile.bak"
fi

log "URL=$url"
log "File=$configFile"
curl --silent "$url" > "$configFile"

log "Fetch completed."
exit 0

