#!/bin/bash

# Common
source "${0%/*}/config/common"

{

# Check the IP address
# -- Only needed in DHCP situations

# checkFile=$pathRoot/config-ip
# ipCurrent=$(hostname -I)
# ipLast=$(cat "$checkFile")
# echo "$ipCurrent :: $ipLast"
# if [ ! "$ipCurrent" = "$ipLast" ]
# then
#    $pathRoot/notify "IP : $ipCurrent" "Current IP is $ipCurrent"
#    echo $ipCurrent > $checkFile
#    log "IP notification triggered"
# fi


# Update the schedule if needed
#checkFile=$pathRoot/config-schedule
#if [ ! -s "$checkFile" ] || test `find "$checkFile" -mtime +59`
#then
# $pathRoot/schedule update
#fi

# See if we need to upload files 
ls -l $pathRoot/video/*.mp4 > /dev/null 2>&1
if [ "$?" = "0" ]
then
 log "Uploading"
 $pathRoot/upload &
fi

} | tee -a $logFile


