#!/bin/bash
# usage : notify "[subject]" "[body]"

# Common
source "${0%/*}/config/common"

host=$(hostname)
ip=$(hostname -I)

to=$notify
subject="$1"
body="$2"

if [ ! -e $notify ] 
then
  log "Notifying $to : $subject / $body"
  sendEmail -f "$host@$ip" -t "$to" -u "$subject" -m "$body\n($host/$ip)" -s "mail.lynchburg.edu":25 -o tls=no
fi



