#!/bin/bash

# Common
source "${0%/*}/config/common"
source "${0%/*}/config/machine"

item=${1,,}

# Validations..
if [ "$item" == "" ]
then
 log "No item provided."
 exit 1
fi

case "$item" in

    "meta-epoch" )

           epoch=$2
           if [ ! "$epoch" == "" ]
           then

                    sourceData=$(grep -h "|" "$pathRoot/config/meta") 

                    while IFS="|" read -r scheduleid start stop title description owner
                    do
                         #take out any end-of-line characters from the last variable
                         owner=$(echo "$owner"|tr -d '\r' )

                         checkStart=$(( $start - 20 ))
                         checkStop=$(( $stop + 5 ))

                         if [[ "$checkStart" -le "$epoch" && "$epoch" -le "$checkStop" ]] 
                         then
                               echo "$title|$description|$owner"
                         fi

                    done <<< "$sourceData"
           fi
           ;;
           
	

    "meta-id" )
           metaMatch=$2
           if [ ! "$metaMatch" == "" ]
           then
              grep "$metaMatch" "$pathRoot/config/meta"
           fi
           ;;



    "meta-refresh" )

           for file in video/*uploaded
           do

              basename=$(basename "$file")

  	          IFS='.' read -a names <<< "$basename"
              epoch=${names[0]}

              log "-----------------------------"
              log "$epoch"

              info=$($pathRoot/parse meta-epoch "$epoch")
              if [ "$info" == "" ]
              then
                echo "No metadata for $epoch"
              else

		       # Parse out the metadata into a curl-friendly string
		       IFS='|' read -a meta <<< "$info"

               metaTitle=${meta[0]}
               metaDescription=${meta[1]}
               metaUser=${meta[2]}
               metaUploaded=$(date -d@"$epoch" +"%F %r")

		       # Try to update it..
               set -x
               info=$(/usr/bin/curl -F "mediaKeywords=$roomID $epoch" -F "update=Y" -F "public=0" -F "uploadedUser=$metaUser"  -F "uploaded=$metaUploaded" -F "title=$metaTitle" -F "description=$metaDescription" "$urlUpload")
               set +x
               log "$info"

               # Wasn't there?  Upload it ;)
               if [[ "$info" == "error:no media name" ]] 
               then
                 log "---- UPLOAD START --- "
                 set -x
                 info=$(/usr/bin/curl -F "batchMode=Y" -F "public=0" -F "uploadedUser=$metaUser"  -F "uploaded=$metaUploaded" -F "title=$metaTitle" -F "description=$metaDescription" -F "keywords=$roomID $basename lecture" -F "file=@$file" "$urlUpload")
                 set +x
                 log "---- UPLOAD END --- "
                 log "$info"
               fi

               
              fi
              log "-----------------------------"

           done

           ;;           



    "schedule" )
					scheduleCounter=1

					inputLocal="$pathRoot/config/schedule-local"
                    touch $inputLocal

					inputRemote="$pathRoot/config/schedule-remote"
                    touch $inputRemote

					outputSchedule="$pathRoot/config/init-schedule"
					backup "$outputSchedule"

                    outputMeta="$pathRoot/config/meta"
					backup "$outputMeta"

                    sourceData=$(grep -h "|" "$inputLocal" "$inputRemote") 

                    echo "del schedule" > $outputSchedule
                    echo "" > $outputMeta

                    while IFS="|" read -r courseid start stop title description owner
					do

                      sid="s$scheduleCounter-$courseid"

					  startEpoch=$(date +"%s" -d "$start")
					  stopEpoch=$(date +"%s" -d "$stop")

					  startTimestamp=$(date +"%Y/%m/%d-%H:%M:%S" -d @$startEpoch)

                      # Trim off 5 seconds
                      let stopEpoch=stopEpoch-5
					  stopTimestamp=$(date +"%Y/%m/%d-%H:%M:%S" -d @$stopEpoch)

					  meta="$sid|$startEpoch|$stopEpoch|$title|$description / $start to $stop|$owner"

						{
							echo ""
							echo "new   $sid-start schedule"
							echo "setup $sid-start date $startTimestamp"
							echo "setup $sid-start append control recorder stop"
							echo "setup $sid-start append control recorder play"
							echo "setup $sid-start enabled"
							echo ""
							echo "new   $sid-stop schedule"
							echo "setup $sid-stop date $stopTimestamp"
							echo "setup $sid-stop append control recorder stop"
							echo "setup $sid-stop enabled"

						} >> "$outputSchedule"

                        {
                            echo "$meta"
                        } >> "$outputMeta"

      		         let scheduleCounter=scheduleCounter+1
       			done  <<< "$sourceData"

               log "Parsed $scheduleCounter items into $outputSchedule"
               ;;


           *) echo "Invalid action verb."
             ;;    

esac

exit 0

