#!/bin/bash

# Common
source "${0%/*}/config"

device="/dev/video0"

# Logitech C920
#v4l2-ctl -d $device -v width=1280,height=720,pixelformat=1
#v4l2-ctl -d $device --set-parm=24

#Default Settings
v4l2-ctl -d $device -c brightness=128
v4l2-ctl -d $device -c contrast=128
v4l2-ctl -d $device -c saturation=128
v4l2-ctl -d $device -c white_balance_temperature_auto=1
v4l2-ctl -d $device -c gain=0
v4l2-ctl -d $device -c power_line_frequency=2
#v4l2-ctl -d $device -c white_balance_temperature=4000
v4l2-ctl -d $device -c sharpness=128
v4l2-ctl -d $device -c backlight_compensation=0
v4l2-ctl -d $device -c exposure_auto=3
#v4l2-ctl -f $device -c exposure_absolute=250
#v4l2-ctl -f $device -c exposure_auto_priority=0
v4l2-ctl -d $device -c pan_absolute=0
v4l2-ctl -d $device -c tilt_absolute=0
v4l2-ctl -d $device -c focus_auto=1
#v4l2-ctl -d $device -c focus_absolute=100
#v4l2-ctl -d $device -c zoom_absolute=0


# Custom Settings
#v4l2-ctl -d $device -c focus_auto=0
#v4l2-ctl -d $device -c focus_absolute=1
#v4l2-ctl -d $device -c zoom_absolute=128
#v4l2-ctl -d $device -c sharpness=188

#v4l2-ctl -d $device -c pan_absolute=-14400
#v4l2-ctl -d $device -c tilt_absolute=10400

