#!/bin/bash
# Common
source "${0%/*}/config/common"

# Allow passing the room on the command line
if [ "$1" != "" ] && [ "$1" != "update" ]
then
 roomID="$1"
 shift
fi

  
# Get the schedule
url="$urlInfo?room=$roomID&days=30"
log "Obtaining Schedule for $roomID"
log $url
wget --quiet -O $pathRoot/config/schedule "$url"

# Update VLM if asked
if [ "$1" == "update" ]
then
 log "Appying schedule to current session"
 wget --quiet -O "$logFile" http://localhost:8888/cmd.xml?command=load%20config/schedule 
fi

log "Done."

