#!/bin/bash
# Common
source "${0%/*}/config/common"

# Allow passing the room on the command line
if [ "$1" != "" ] && [ "$1" != "update" ]
then
 roomID="$1"
 shift
fi

# Read the media file to get the output-template 
template=$(sed -n 's/#template=//p' config/media ) 

# Get the schedule
url="$urlInfo"

log "Obtaining Schedule for $roomID"
log "From : $url"

curl --silent "$url" --data "room=$roomID&days=30&template=$template" > config/schedule
# wget --post-data="$post" --quiet -O $pathRoot/config/schedule "$url"

# Update VLM if asked
if [ "$1" == "update" ]
then
 log "Appying schedule to current session"
 curl --silent http://localhost:8888/cmd.xml?command=load%20config/schedule > "$logFile"
fi

log "Done."

