#!/bin/bash

source "${0%/*}/config/common"

#  if [ $(whoami) != "root" ]
#  then
#    echo "Setup must be run as root (ie. sudo ./setup)"
#    exit
#  fi

function addJob {
  command=$1
  cat <(fgrep -i -v "$command" <(crontab -l)) <(echo -e "$command") | crontab -
}


  echo "----------------------------"
  echo "Current Machine Settings"
  echo "----------------------------"
  echo "      ROOM : $room"
  echo "  ROOMNAME : $roomName"
  echo "----------------------------"
  echo ""
 
  read -p "New Room Code ($room) : " value
  [ "$value" == "" ] || room=${value//[[:space:]]/}

  read -p "New Room Description ($roomName) : " value
  [ "$value" == "" ] || roomName=$value

  echo -e "#--- Configuration updated $(date)\n\nroom=$room\nroomName=\"$roomName\"" > $pathRoot/config/machine
  chown capture $pathRoot/config/machine
    
  mkdir $pathRoot/video
  chown capture $pathRoot/video

  mkdir $pathRoot/log
  chown capture $pathRoot/log

  mkdir $pathRoot/config
  chown capture $pathRoot/log

  echo "----------------------------"
  echo "New Machine Settings (written to $pathRoot/config/machine)"
  echo "----------------------------"
  echo "      ROOM : $room"
  echo "  ROOMNAME : $roomName"
  echo ""

  addJob "@reboot /home/capture/Camera/start"
  addJob "05,35 * * * * /home/capture/Camera/upload"
  addJob "0     1 * * 0 /home/capture/Camera/schedule"
  addJob "5     1 * * 0 /home/capture/Camera/stop"
  addJob "10     1 * * 0 /home/capture/Camera/start"

  echo ""
  echo "... setup complete."
  
  /home/capture/Camera/schedule

  /home/capture/Camera/start
    





