#!/bin/bash

source "${0%/*}/config"


  if [ $(whoami) != "root" ]
  then
    echo "Setup must be run as root (ie. sudo ./setup)"
    exit
  fi

  ip=$(hostname -I)
  hostname=$(hostname)
  mac=$(ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
 
  echo "----------------------------"
  echo "Current Settings"
  echo "----------------------------"
  echo "        IP : $ip"
  echo "       MAC : $mac"
  echo "  HOSTNAME : $hostname"
  echo "      ROOM : $room"
  echo "  ROOMNAME : $roomName"
  echo "----------------------------"
  echo ""
 
  read -p "New Room Code ($room) : " value
  [ "$value" == "" ] || room=${value//[[:space:]]/}

  read -p "New Room Description ($roomName) : " value
  [ "$value" == "" ] || roomName=$value

  echo -e "#--- Configuration updated $(date)\n\nroom=$room\nroomName=\"$roomName\"" > $pathRoot/config-settings

  echo "----------------------------"
  echo "New Settings (written to $pathRoot/config-settings)"
  echo "----------------------------"
  echo "      ROOM : $room"
  echo "  ROOMNAME : $roomName"
  echo ""


  propername="CAPTURE-$room"
  if [ "$hostname" != "$propername" ] 
  then
    while true; do
    read -p "Do you want to set the hostname to $propername (Y/N)? " answer
    case $answer in
        [Yy]* )  echo $propername > /etc/hostname
                 sed -i "s/127.0.1.1.*$hostname/127.0.1.1\t$propername/g" /etc/hosts
                 sudo reboot
                 break
                 ;;

        [Nn]* ) echo "You must manually reboot for the change to take effect"
                break
                ;;

        * ) echo "Please answer yes or no.";;
    esac
    done

  fi

  echo ""
  echo "... setup complete."






