#!/bin/bash

source "${0%/*}/config/common"

#  if [ $(whoami) != "root" ]
#  then
#    echo "Setup must be run as root (ie. sudo ./setup)"
#    exit
#  fi


  echo "----------------------------"
  echo "Current Machine Settings"
  echo "----------------------------"
  echo "      ROOM : $roomID"
  echo "  ROOMNAME : $roomName"
  echo "----------------------------"
  echo ""
 
  read -p "New Room Code ($roomID) : " value
  [ "$value" == "" ] || roomID=${value//[[:space:]]/}

  read -p "New Room Description ($roomName) : " value
  [ "$value" == "" ] || roomName=$value

  echo -e "#--- Configuration updated $(date)\n\nroomID=$roomID\nroomName=\"$roomName\"" > $pathRoot/config/machine
  chown capture $pathRoot/config/machine
    
  mkdir -p $pathRoot/video
  chown capture $pathRoot/video

  mkdir -p $pathRoot/log
  chown capture $pathRoot/log

  mkdir -p $pathRoot/config
  chown capture $pathRoot/config

  echo "----------------------------"
  echo "Machine Settings ($pathRoot/config/machine)"
  echo "----------------------------"
  echo "      ROOM : $room"
  echo "  ROOMNAME : $roomName"
  echo ""

  crontab $pathRoot/config/crontab

  echo ""
  echo "... setup complete."
  
  /home/capture/Camera/schedule

  /home/capture/Camera/start
    





