#!/bin/bash

# Common
source "${0%/*}/config/common"

if [[ -z "$roomID" ]]; then
 log "Cannot start!  Run ./setup to configure"
 exit 1
fi

# Move to the home directory
cd $pathRoot

# Make sure everything is stopped..
$pathRoot/stop

if [ "$1" == "debug" ]; then
 logVLC=$pathRoot/log/vlc.log
 optionsVLC=-vvvvv
else
 logVLC=/dev/null
fi

# Start the HTTP interface
cvlc $optionsVLC --intf=http  --http-port=8888  --http-src="$pathRoot"  --vlm-conf="$pathRoot/config/media"  >> "$logVLC" 2>&1  &
log "Started VLC (logging to $logVLC)"

# Sleep for a bit, then set the camera options
sleep 2
source $pathRoot/config/camera

# Notify that we're running
$pathRoot/notify "Capture Started."

# Give the web address
  ip=$(hostname -I)
  hostname=$(hostname)
  mac=$(ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
 
  echo "----------------------------"
  echo "Machine Settings"
  echo "----------------------------"
  echo "        IP : $ip"
  echo "       MAC : $mac"
  echo "  HOSTNAME : $hostname"
  echo "    MANAGE : http://$ip:8888"
  echo "----------------------------"
  
