#!/bin/bash

# Common
source "${0%/*}/config"
if [[ -z "$room" ]]; then
 log "Cannot start!  Run sudo ./setup to configure"
 exit 1
fi


# Make sure all the necessary paths exists
[ -d "$pathLog" ] || mkdir -p "$pathLog"
[ -d "$pathVideo" ] || mkdir -p "$pathVideo"


# Make sure everything is stopped..
$pathRoot/stop

logVLC=$pathRoot/log/vlc.log
#logVLC=/dev/null

# Start the HTTP interface
cvlc --quiet --intf=http  --http-port=8888  --http-src="$pathRoot"  --vlm-conf="$pathRoot/config-media"  >> "$logVLC" 2>&1  &
log "VLC Launched (logging to $logVLC)"

# Sleep for a bit, then set the camera options
log "Making camera settings.. stand by."
sleep 2
$pathRoot/quality


# Notify that we're running
$pathRoot/notify "Capture Started"
