#!/bin/bash

# Common
source "${0%/*}/config/common"

if [[ -z "$room" ]]; then
 log "Cannot start!  Run ./setup to configure"
 exit 1
fi


# Make sure all the necessary paths exists
[ -d "$pathLog" ] || mkdir -p "$pathLog"
[ -d "$pathVideo" ] || mkdir -p "$pathVideo"


# Make sure everything is stopped..
$pathRoot/stop

logVLC=$pathRoot/log/vlc.log
#logVLC=/dev/null

# Start the HTTP interface
cvlc -vvvvvv  --intf=http  --http-port=8888  --http-src="$pathRoot"  --vlm-conf="$pathRoot/config/media"  >> "$logVLC" 2>&1  &
log "Started VLC (logging to $logVLC)"

# Sleep for a bit, then set the camera options
sleep 2
source $pathRoot/config/camera

# Notify that we're running
$pathRoot/notify "Capture Started."

# Give the web address
  ip=$(hostname -I)
  hostname=$(hostname)
  mac=$(ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
 
  echo "----------------------------"
  echo "Machine Settings"
  echo "----------------------------"
  echo "        IP : $ip"
  echo "       MAC : $mac"
  echo "  HOSTNAME : $hostname"
  echo "    MANAGE : http://$ip:8888"
  echo "----------------------------"
  
