#!/bin/bash

# Common
source "${0%/*}/config/common"

touch $logFile
{
   #  Find all the files
   for file in $(ls $pathVideo/*.mp4)
   do

      if [ ! -z "$file" ] && [ -s $file ]  
      then

        isBusy=$(lsof $file)
        if [ ! -z "$isBusy" ]
        then
          log "Ignoring $file"

        else
           log "Found $file"

           # If the filename is a date, use it as the start time
           asOf=$(basename "$file")

           asOf="${asOf%.*}"
           date -d "$asOf" > /dev/null 2>&1
           if [ $? -eq 1 ]
           then
             #.. otherwise, use the last modified time of the file
             asOf=$(date "+$formatISO" -d "$(stat -c "%y" $file)")
           fi

           # Ask the server for info about the class meeting at that time
           url="$urlInfo?room=$roomID&asOf=$asOf&mode=meeting"
           log "Calling $url"
           info=$(curl -sL "$url")
           log "Got $info"

           # Post to the media server
           cmd="curl -F \"batchMode=Y\" $info -F \"file=@$file\" $urlUpload"
           log "$cmd"
           info=$(eval "$cmd")

           # Archive the original file
           if [[ "$info" == *Success* ]]
           then
                log "$file was sucessfully uploaded"
                mv "$file" "$file.uploaded"
           else
                log "$info"
                $pathRoot/notify "Upload Error" "$file\n$info"
                mv "$file" "$file.error"
           fi

        fi

      fi

done

# Remove uploaded stuff older than 1 week
find "$pathVideo/*.uploaded" -mtime +5 -exec rm {} \;

# Alert if space is low
spaceUsed=$(df $pathVideo | tail -1 | awk '{print $5}' | sed 's/%//g')
[[ $spaceUsed -gt 70 ]] && $pathRoot/notify  "Storage Space Used : $spaceUsed%"


} | tee -a $logFile

