#!/bin/bash

function log {
   echo "$1"
}
function backup {
	if [ ! -z "$1" ]
	then
	  mv "$1" "$1.bak"
	fi
}
function include {
	if [ ! -z "$1" ]
	then
	  source $1
	fi
}


# ------------
# Read in the settings for this unit
# ------------
source "${0%/*}/config/machine"

# ------------
# Common  for all scripts
# -----------

# Create a log file for whatever script is running
logFile="${0%/*}/log/${0##*/}.log"

formatISO="%Y-%m-%dT%TZ"

# Local paths
pathRoot=$(pwd)
pathLog="$pathRoot/log"
pathVideo="$pathRoot/video"
pathConfig="$pathRoot/config"



