#!/bin/bash

# Common logging function
function log {
  echo "$(date) : $1"
}

# ------------
# Read in the settings for this unit
# ------------
source "${0%/*}/config/machine"


# ------------
# Common  for all scripts
# -----------

# Create a log file for whatever script is running
logFile="${0%/*}/log/${0##*/}.log"

formatISO="%Y-%m-%dT%TZ"

# Local paths
pathRoot="/home/capture/Camera"
pathLog="$pathRoot/log"
pathVideo="$pathRoot/video"
pathConfig="$pathRoot/config"

# URLs
urlInfo="http://apps.lynchburg.edu/campus/system/public/calendar/roominfo.asp"
urlUpload="http://media.lynchburg.edu/upload.php"


