#!/bin/bash

function log {
   echo "$1"
}
function backup {
	if [ ! -z "$1" ]
	then
	  mv "$1" "$1.bak"
	fi
}
function include {
	if [ ! -z "$1" ]
	then
	  source $1
	fi
}


pathRoot="/home/capture/Camera"
pathLog="$pathRoot/log"
pathVideo="$pathRoot/video"
pathConfig="$pathRoot/config"

logFile="${0%/*}/log/${0##*/}.log"



